### ISSUE TITLE
Accessoire introuvable

### ISSUE THREAD

**Issue by Helethom** [NebzHB/plugin-homebridge#14]
Bonjour,
Je vous remercie pour le développement de ce plug-in que j'ai hate d'essayer.
Homebridge a fonctionné par intermittence pendant une journée sur ma Jeedom Smart (déconnexions très fréquentes). Puis, dans l'après midi, je n'ai plus eu du tout de connexion depuis l'application maison de mon iPad. Après plusieurs redémarrages de ma Jeedom, j'ai tenté des réparations de homebrige, puis des réparations+installations et enfin une suppression du plugin et réinstallation depuis le market. Le résultat est toujours le même:
-Je ne vois pas d'erreur dans les logs de HomeBridge
-Le deamon est bien lancé
-Lorsque je scande le QR code pour ajouter le pont à HomeBridge, l'accessoire est "introuvable".
Pourriez-vous m'indiquer une marche à suivre pour résoudre ce problème?
En vous remerciant par avance,
Bonne soirée,
Thomas

**Comment by NebzHB** [comment]
Bonjour,
Le problème ne vient pas du plugin mais de votre réseau, je ferme cette Issue, on continue sur le forum.
Bien à vous,
Nebz
