### ISSUE TITLE
Siri can't set temperature on Netatmo thermostat

### ISSUE THREAD

**Issue by dayar** [NebzHB/plugin-homebridge#6]
I installed last version of homebrige plugin for jeedom.
Previously i have Movile app working with homebridge, I have Netatmo thermostat working through homebridge with Home app, and I could set the temerature with Siri.
Since I updated to the new plugin I can set the temerature with Home app, but if I tell Siri to adjust the temperature, Siri replies that he has adjusted it, but no change is made in the Home app.
Is it possible that it is a bug of the plugin?
Thanks in advance.

**Comment by NebzHB** [comment]
Dear Dayar,

Thank you for using the Homebridge plugin !

Could you please provide the homebridge_daemon log (log level = info) and indicate inside this one where you tell Siri to set a temperature. Then another indication where you do that with the Home app.  Are you french speaking native or english ?

**Comment by NebzHB** [comment]
No reply for 24 days
